environment:
  type: basic

  init_pos: [0, 5]
  target_pos: [8, 10]
  init_vel: [3, 5]

  gravity: [0, -30]
  bounds: [[0, 10], [0, 15]]

  tap_vel: 15
  min_tap_interval: 0.1

  ball_radius: 0.2

  ground_threshold: 0.5

  basket_radius: 0.6
  basket_ring_radius: 0.08
