environment:
  air_friction: 0.01
  ball_radius: 0.3
  basket_radius: 0.6170457070940262
  basket_ring_radius: 0.0766254895065647
  board_height: 4
  board_width: 0.55
  bounds:
  - - 0
    - 10
  - - 0
    - 15
  coeff_bounce: 0.6
  gravity:
  - 0
  - -25
  ground_threshold: 0.5
  init_pos:
  - 0
  - 5
  init_vel:
  - 3
  - 5
  min_tap_interval: 0.1
  tap_vel: 15
  target_pos:
  - 8
  - 10
  type: basic
